// Initializes the ShadowLend markets with Pyth feed ids on the configured
// cluster.
//
//   1. Deploy the program:  solana program deploy target/deploy/shadow_lend.so --url devnet
//   2. Run this script:     TS_NODE_TRANSPILE_ONLY=true ANCHOR_PROVIDER_URL=https://api.devnet.solana.com \
//                           ANCHOR_WALLET=~/.config/solana/id.json yarn ts-node migrations/initialize-markets.ts
//   3. It writes the resulting mints + derived Pyth price-update addresses
//      into app/config.js automatically.

import * as anchor from "@coral-xyz/anchor";
import { Program, BN } from "@coral-xyz/anchor";
import { Keypair, PublicKey, SystemProgram } from "@solana/web3.js";
import { TOKEN_PROGRAM_ID } from "@solana/spl-token";
import * as fs from "fs";
import * as path from "path";

const DECIMALS = 9;

// Pyth Solana Receiver program id (same on mainnet and devnet). Stored in
// config.js so the client can locate PriceUpdateV2 accounts by feed id.
const PYTH_RECEIVER = new PublicKey(
  "rec5EKMGg6MxZYaMdyBfgwp4d5rB9T1VQH5pJv5LtFJ"
);

// Each market: a real test SPL mint, a PDA-owned vault, its own max LTV,
// and the Pyth feed id used to value its collateral and debt.
const MARKETS = [
  {
    id: "sol",
    label: "SOL",
    name: "Solana",
    maxLtvBps: 8000,
    claimUi: 1_000,
    feedHex: "ef0d8b6fda2ceba41da15d4095d1da392a0d2f8ed0c6c7bc0f4cfac8c280b56d",
  },
  {
    id: "usdc",
    label: "USDC",
    name: "USD Coin",
    maxLtvBps: 8500,
    claimUi: 50_000,
    feedHex: "eaa020c61cc479712813461ce153894a96a6c00b21ed0cfc2798d1f9a9e9c94a",
  },
  {
    id: "btc",
    label: "BTC",
    name: "Wrapped Bitcoin",
    maxLtvBps: 7500,
    claimUi: 50,
    feedHex: "e62df6c8b4a85fe1a67db44dc12de5db330f7ac66b72dc658afedf0f4a415b43",
  },
];

const seed = (s: string) => Buffer.from(s);
const hex = (h: string) => Buffer.from(h, "hex");
const toBase = (ui: number) =>
  new BN(ui).mul(new BN(10).pow(new BN(DECIMALS)));

async function main() {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);
  const program = anchor.workspace.ShadowLend as Program<any>;
  const admin = (provider.wallet as anchor.Wallet).payer;
  console.log("program:", program.programId.toBase58());
  console.log("admin:  ", admin.publicKey.toBase58());

  const resolved: Record<string, string> = {};

  for (const m of MARKETS) {
    const feedId = hex(m.feedHex);
    if (feedId.length !== 32)
      throw new Error(`bad feed_id length for ${m.label}: ${feedId.length}`);

    const mint = Keypair.generate();
    const [marketPda] = PublicKey.findProgramAddressSync(
      [seed("market"), mint.publicKey.toBuffer()],
      program.programId
    );
    const [authority] = PublicKey.findProgramAddressSync(
      [seed("auth"), mint.publicKey.toBuffer()],
      program.programId
    );
    const [vault] = PublicKey.findProgramAddressSync(
      [seed("vault"), mint.publicKey.toBuffer()],
      program.programId
    );

    console.log(`\n[${m.label}]`);
    console.log(`  mint       ${mint.publicKey.toBase58()}`);
    console.log(`  market PDA ${marketPda.toBase58()}`);
    console.log(`  vault      ${vault.toBase58()}`);

    const sig = await program.methods
      .initializeMarket(toBase(m.claimUi), m.maxLtvBps, Array.from(feedId))
      .accounts({
        admin: admin.publicKey,
        market: marketPda,
        mint: mint.publicKey,
        authority,
        vault,
        systemProgram: SystemProgram.programId,
        tokenProgram: TOKEN_PROGRAM_ID,
      })
      .signers([mint])
      .rpc();
    console.log(`  ✓ tx ${sig}`);

    resolved[m.id] = mint.publicKey.toBase58();
  }

  writeConfig(resolved);
}

function writeConfig(mints: Record<string, string>) {
  const configPath = path.join(__dirname, "..", "app", "config.js");
  const marketsJs = MARKETS.map(
    (m) =>
      `    {\n` +
      `      id: "${m.id}",\n` +
      `      label: "${m.label}",\n` +
      `      name: "${m.name}",\n` +
      `      mint: "${mints[m.id]}",\n` +
      `      maxLtvBps: ${m.maxLtvBps},\n` +
      `      claimUi: ${m.claimUi},\n` +
      `      decimals: ${DECIMALS},\n` +
      `      feedHex: "${m.feedHex}",\n` +
      `    }`
  ).join(",\n");

  const body =
    `// ShadowLend frontend config.\n` +
    `// Regenerated by migrations/initialize-markets.ts after each deploy.\n` +
    `window.SHADOW_LEND_CONFIG = {\n` +
    `  cluster: "devnet",\n` +
    `  rpcUrl: "https://api.devnet.solana.com",\n` +
    `  programId: "5jqXbgExBEnKPahsQineFmMJHNcEvwnniiYvDy81bZCF",\n` +
    `  pythReceiverProgramId: "${PYTH_RECEIVER.toBase58()}",\n` +
    `  markets: [\n${marketsJs},\n  ],\n` +
    `};\n`;

  fs.writeFileSync(configPath, body);
  console.log("\n✓ wrote app/config.js with", MARKETS.length, "markets");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
