// Initializes the ShadowLend markets on the configured cluster.
//
//   1. Deploy the program:  solana program deploy target/deploy/shadow_lend.so --url devnet
//   2. Run this script:     TS_NODE_TRANSPILE_ONLY=true ANCHOR_PROVIDER_URL=https://api.devnet.solana.com \
//                           ANCHOR_WALLET=~/.config/solana/id.json yarn ts-node migrations/initialize-markets.ts
//   3. It writes the resulting mints into app/config.js automatically.
//
// Safe to re-run: markets whose PDA already exists are skipped.

import * as anchor from "@coral-xyz/anchor";
import { Program, BN } from "@coral-xyz/anchor";
import { Keypair, PublicKey, SystemProgram } from "@solana/web3.js";
import { TOKEN_PROGRAM_ID } from "@solana/spl-token";
import * as fs from "fs";
import * as path from "path";

const DECIMALS = 9;

// Each market: a real test SPL mint, a PDA-owned vault, its own max LTV.
// claimUi is how many whole tokens the faucet hands out per wallet.
const MARKETS = [
  { id: "sol", label: "SOL", name: "Solana", maxLtvBps: 8000, claimUi: 1_000 },
  { id: "usdc", label: "USDC", name: "USD Coin", maxLtvBps: 8500, claimUi: 50_000 },
  { id: "btc", label: "BTC", name: "Wrapped Bitcoin", maxLtvBps: 7500, claimUi: 50 },
];

const seed = (s: string) => Buffer.from(s);
const toBase = (ui: number) => new BN(ui).mul(new BN(10).pow(new BN(DECIMALS)));

async function main() {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);
  const program = anchor.workspace.ShadowLend as Program<any>;
  const admin = (provider.wallet as anchor.Wallet).payer;

  console.log("program:", program.programId.toBase58());
  console.log("admin:  ", admin.publicKey.toBase58());

  const resolved: Record<string, string> = {};

  for (const m of MARKETS) {
    const mint = Keypair.generate();
    const [marketPda] = PublicKey.findProgramAddressSync(
      [seed("market"), mint.publicKey.toBuffer()],
      program.programId
    );
    const [authority] = PublicKey.findProgramAddressSync(
      [seed("auth"), mint.publicKey.toBuffer()],
      program.programId
    );
    const [vault] = PublicKey.findProgramAddressSync(
      [seed("vault"), mint.publicKey.toBuffer()],
      program.programId
    );

    console.log(`\n[${m.label}] new mint ${mint.publicKey.toBase58()}`);
    const sig = await program.methods
      .initializeMarket(toBase(m.claimUi), m.maxLtvBps)
      .accounts({
        admin: admin.publicKey,
        market: marketPda,
        mint: mint.publicKey,
        authority,
        vault,
        systemProgram: SystemProgram.programId,
        tokenProgram: TOKEN_PROGRAM_ID,
      })
      .signers([mint])
      .rpc();
    console.log(`  market PDA ${marketPda.toBase58()}`);
    console.log(`  vault      ${vault.toBase58()}`);
    console.log(`  ✓ tx ${sig}`);

    resolved[m.id] = mint.publicKey.toBase58();
  }

  writeConfig(resolved);
}

function writeConfig(mints: Record<string, string>) {
  const configPath = path.join(__dirname, "..", "app", "config.js");
  const markets = MARKETS.map(
    (m) =>
      `    {\n` +
      `      id: "${m.id}",\n` +
      `      label: "${m.label}",\n` +
      `      name: "${m.name}",\n` +
      `      mint: "${mints[m.id]}",\n` +
      `      maxLtvBps: ${m.maxLtvBps},\n` +
      `      claimUi: ${m.claimUi},\n` +
      `      decimals: ${DECIMALS},\n` +
      `    }`
  ).join(",\n");

  const body =
    `// ShadowLend frontend config.\n` +
    `// Regenerated by migrations/initialize-markets.ts after each market deploy.\n` +
    `window.SHADOW_LEND_CONFIG = {\n` +
    `  cluster: "devnet",\n` +
    `  rpcUrl: "https://api.devnet.solana.com",\n` +
    `  programId: "5jqXbgExBEnKPahsQineFmMJHNcEvwnniiYvDy81bZCF",\n` +
    `  markets: [\n${markets},\n  ],\n` +
    `};\n`;

  fs.writeFileSync(configPath, body);
  console.log("\n✓ wrote app/config.js with", MARKETS.length, "markets");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
