// ShadowLend frontend config.
// Regenerated by migrations/initialize-markets.ts after each deploy.
// PriceUpdateV2 accounts on devnet rotate as sponsors come and go, so the
// client resolves the freshest one per feed at runtime via getProgramAccounts.
window.SHADOW_LEND_CONFIG = {
  cluster: "devnet",
  rpcUrl: "https://api.devnet.solana.com",
  programId: "5jqXbgExBEnKPahsQineFmMJHNcEvwnniiYvDy81bZCF",
  pythReceiverProgramId: "rec5EKMGg6MxZYaMdyBfgwp4d5rB9T1VQH5pJv5LtFJ",
  markets: [
    {
      id: "sol",
      label: "SOL",
      name: "Solana",
      mint: "2dCnFSkQxpygGZt8n1vRzQkLqgLT8NgUVjyDKMs5Mfm3",
      maxLtvBps: 8000,
      claimUi: 1000,
      decimals: 9,
      feedHex: "ef0d8b6fda2ceba41da15d4095d1da392a0d2f8ed0c6c7bc0f4cfac8c280b56d",
    },
    {
      id: "usdc",
      label: "USDC",
      name: "USD Coin",
      mint: "985NmTuHb1hqgeyAzi171KQfjx8mYDERP3PssBcRPwiA",
      maxLtvBps: 8500,
      claimUi: 50000,
      decimals: 9,
      feedHex: "eaa020c61cc479712813461ce153894a96a6c00b21ed0cfc2798d1f9a9e9c94a",
    },
    {
      id: "btc",
      label: "BTC",
      name: "Wrapped Bitcoin",
      mint: "AJHDBSGEpuezkxNTKTBsrAUBKraKMvahaZt22vCCPDTx",
      maxLtvBps: 7500,
      claimUi: 50,
      decimals: 9,
      feedHex: "e62df6c8b4a85fe1a67db44dc12de5db330f7ac66b72dc658afedf0f4a415b43",
    },
  ],
};
