// ShadowLend frontend config.
// Regenerated by migrations/initialize-markets.ts after each deploy.
window.SHADOW_LEND_CONFIG = {
  cluster: "devnet",
  rpcUrl: "https://api.devnet.solana.com",
  programId: "5jqXbgExBEnKPahsQineFmMJHNcEvwnniiYvDy81bZCF",
  pythReceiverProgramId: "rec5EKMGg6MxZYaMdyBfgwp4d5rB9T1VQH5pJv5LtFJ",
  markets: [
    {
      id: "sol",
      label: "SOL",
      name: "Solana",
      mint: "F2nGPw75ytic5dbFCFueehEhcrRYWn5rwKoSU8wJb61U",
      maxLtvBps: 8000,
      claimUi: 1000,
      decimals: 9,
      feedHex: "ef0d8b6fda2ceba41da15d4095d1da392a0d2f8ed0c6c7bc0f4cfac8c280b56d",
      aprDecimal: 1,
    },
    {
      id: "usdc",
      label: "USDC",
      name: "USD Coin",
      mint: "JEGFtq2JJg6J7Z7XxGgPxziPgCEvMZgnEZoJRyY6VzG1",
      maxLtvBps: 8500,
      claimUi: 50000,
      decimals: 9,
      feedHex: "eaa020c61cc479712813461ce153894a96a6c00b21ed0cfc2798d1f9a9e9c94a",
      aprDecimal: 2,
    },
    {
      id: "btc",
      label: "BTC",
      name: "Wrapped Bitcoin",
      mint: "EXJxTpbYLgB7GpynjYjjzz8JMx5FPKajE8ErLGuaCjnT",
      maxLtvBps: 7500,
      claimUi: 50,
      decimals: 9,
      feedHex: "e62df6c8b4a85fe1a67db44dc12de5db330f7ac66b72dc658afedf0f4a415b43",
      aprDecimal: 0.5,
    },
  ],
};
