// ShadowLend frontend config.
// Regenerated by migrations/initialize-markets.ts after each market deploy.
window.SHADOW_LEND_CONFIG = {
  cluster: "devnet",
  rpcUrl: "https://api.devnet.solana.com",
  programId: "5jqXbgExBEnKPahsQineFmMJHNcEvwnniiYvDy81bZCF",
  markets: [
    {
      id: "sol",
      label: "SOL",
      name: "Solana",
      mint: "DjDLBKuUbNXbtiLAqdonbqGYviFbGrCr1m3Lop5BH47o",
      maxLtvBps: 8000,
      claimUi: 1000,
      decimals: 9,
    },
    {
      id: "usdc",
      label: "USDC",
      name: "USD Coin",
      mint: "HJCk4kYfb3FpMU5NNrafWC5cXmTZJ8g36EMkpVCcQA7X",
      maxLtvBps: 8500,
      claimUi: 50000,
      decimals: 9,
    },
    {
      id: "btc",
      label: "BTC",
      name: "Wrapped Bitcoin",
      mint: "9xNTtpeRWPzD7BNc3ZbZfTcmt4cD6hUjDZ9BBX6gpX2o",
      maxLtvBps: 7500,
      claimUi: 50,
      decimals: 9,
    },
  ],
};
